---
  - name: import jenkins key from url
    ansible.builtin.rpm_key:
      state: present
      key: "{{ keyr }}"
    when: ansible_os_family == "RedHat"
  
    # For Debian based Os
  - name: Import jenkins key
    apt_key:
      url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
      state: present
    when: ansible_os_family == "Debian"